function simuladorSIR_Fase()
    % ============================================================
    % PARÁMETROS INICIALES
    % ============================================================
    N = 7.9e6;                 % Población de NY
    Y_0 = [N - 10, 10, 0];     % [S(0), I(0), R(0)]
    t_span = 0:1:300;           % Simulación de 300 días
    % Escenario de referencia
    beta_opt = 0.7;
    gamma_opt = 0.3;
    % ============================================================
    % CREACIÓN DE LA INTERFAZ
    % ============================================================
    fig = uifigure( ...
        'Name', 'Simulador SIR Interactivo', ...
        'Position', [100, 50, 1200, 750]);
    % ============================================================
    % EJE 1: DIAGRAMA DE FASE
    % ============================================================
    axFase = uiaxes(fig, ...
        'Position', [50, 350, 520, 350]);
    title(axFase, 'Diagrama de Fase: Infectados vs Susceptibles');
    xlabel(axFase, 'Susceptibles (S)');
    ylabel(axFase, 'Infectados (I)');
    grid(axFase, 'on');
    % Convención utilizada en tu gráfico original
    set(axFase, 'XDir', 'reverse');
    % ============================================================
    % EJE 2: DINÁMICA TEMPORAL DEL MODELO
    % ============================================================
    axTiempo = uiaxes(fig, ...
        'Position', [600, 350, 520, 350]);
    title(axTiempo, 'Dinámica temporal del modelo SIR');
    xlabel(axTiempo, 'Tiempo [días]');
    ylabel(axTiempo, 'Personas');
    grid(axTiempo, 'on');
    % ============================================================
    % PANEL DE RESULTADOS
    % ============================================================
    lblResultados = uilabel(fig, ...
        'Position', [50, 140, 1070, 170], ...
        'VerticalAlignment', 'top', ...
        'FontSize', 14);
    % ============================================================
    % SLIDER BETA
    % ============================================================
    uilabel(fig, ...
        'Position', [100, 100, 180, 22], ...
        'Text', 'Beta (contagio):', ...
        'FontWeight', 'bold');
    sldBeta = uislider(fig, ...
        'Position', [100, 80, 250, 3], ...
        'Limits', [0, 2], ...
        'Value', 2/3);
    % ============================================================
    % SLIDER GAMMA
    % ============================================================
    uilabel(fig, ...
        'Position', [450, 100, 180, 22], ...
        'Text', 'Gamma (recuperación):', ...
        'FontWeight', 'bold');
    sldGamma = uislider(fig, ...
        'Position', [450, 80, 250, 3], ...
        'Limits', [0.01, 1], ...
        'Value', 1/4);
    % ============================================================
    % BOTÓN EXPORTAR
    % ============================================================
    btnExportar = uibutton(fig, ...
        'Position', [850, 70, 180, 35], ...
        'Text', 'Exportar al Workspace', ...
        'ButtonPushedFcn', @(src,event) exportarValores());
    % Actualización de gráficos
    sldBeta.ValueChangedFcn = @(src,event) actualizarGrafica();
    sldGamma.ValueChangedFcn = @(src,event) actualizarGrafica();
    % Dibujar inicialmente
    actualizarGrafica();
    % ============================================================
    % FUNCIÓN PRINCIPAL DE ACTUALIZACIÓN
    % ============================================================
    function actualizarGrafica()
        % --------------------------------------------------------
        % ESCENARIO OPTIMIZADO
        % --------------------------------------------------------
        [t_opt, Y_opt] = ode45( ...
            @(t,y) modeloSIR(t,y,beta_opt,gamma_opt,N), ...
            t_span, Y_0);
        S_opt = Y_opt(:,1);
        I_opt = Y_opt(:,2);
        R_opt = Y_opt(:,3);
        % --------------------------------------------------------
        % ESCENARIO ACTUAL
        % --------------------------------------------------------
        beta_actual = sldBeta.Value;
        gamma_actual = sldGamma.Value;
        [t_act, Y_act] = ode45( ...
            @(t,y) modeloSIR(t,y,beta_actual,gamma_actual,N), ...
            t_span, Y_0);
        S_act = Y_act(:,1);
        I_act = Y_act(:,2);
        R_act = Y_act(:,3);
        % ========================================================
        % MÉTRICAS ESCENARIO OPTIMIZADO
        % ========================================================
        % Total de personas que alguna vez se infectaron
        total_infectados_opt = N - S_opt(end);
        % También puede calcularse como R + I al final
        total_infectados_opt_2 = R_opt(end) + I_opt(end);
        % Pico de infectados simultáneos
        [I_max_opt, idx_opt] = max(I_opt);
        % Día del pico
        dia_pico_opt = t_opt(idx_opt);
        % AUC = personas-día
        auc_opt = trapz(t_opt,I_opt);
        % R0
        R0_opt = beta_opt/gamma_opt;
        % Porcentaje de población infectada
        porcentaje_opt = 100 * total_infectados_opt/N;
        % ========================================================
        % MÉTRICAS ESCENARIO ACTUAL
        % ========================================================
        % Total de personas que alguna vez se infectaron
        total_infectados_act = N - S_act(end);
        % Comprobación alternativa
        total_infectados_act_2 = R_act(end) + I_act(end);
        % Pico de infectados simultáneos
        [I_max_act, idx_act] = max(I_act);
        % Día del pico
        dia_pico_act = t_act(idx_act);
        % AUC
        auc_act = trapz(t_act,I_act);
        % R0
        R0_act = beta_actual/gamma_actual;
        % Porcentaje de población infectada
        porcentaje_act = 100 * total_infectados_act/N;
        % ========================================================
        % GRÁFICO 1: DIAGRAMA DE FASE
        % ========================================================
        cla(axFase);
        hold(axFase,'on');
        % Optimizado
        plot(axFase, ...
            S_opt,I_opt, ...
            'b--', ...
            'LineWidth',2, ...
            'DisplayName', ...
            sprintf('Referencia (\\beta=%.2f, \\gamma=%.2f)', ...
            beta_opt,gamma_opt));
        % Pico optimizado
        plot(axFase, ...
            S_opt(idx_opt),I_max_opt, ...
            'bo', ...
            'MarkerSize',8, ...
            'MarkerFaceColor','b', ...
            'HandleVisibility','off');
        % Actual
        plot(axFase, ...
            S_act,I_act, ...
            'k-', ...
            'LineWidth',2, ...
            'DisplayName', ...
            sprintf('Actual (\\beta=%.2f, \\gamma=%.2f)', ...
            beta_actual,gamma_actual));
        % Pico actual
        plot(axFase, ...
            S_act(idx_act),I_max_act, ...
            'ko', ...
            'MarkerSize',8, ...
            'MarkerFaceColor','k', ...
            'HandleVisibility','off');
        hold(axFase,'off');
        legend(axFase,'Location','northeast');
        % ========================================================
        % GRÁFICO 2: DINÁMICA TEMPORAL
        % ========================================================
        cla(axTiempo);
        hold(axTiempo,'on');
        % Escenario actual
        plot(axTiempo,t_act,S_act, ...
            'LineWidth',2, ...
            'DisplayName','Susceptibles S(t)');
        plot(axTiempo,t_act,I_act, ...
            'LineWidth',2, ...
            'DisplayName','Infectados I(t)');
        plot(axTiempo,t_act,R_act, ...
            'LineWidth',2, ...
            'DisplayName','Recuperados R(t)');
        % Línea vertical del pico
        xline(axTiempo, ...
            dia_pico_act, ...
            '--', ...
            'DisplayName', ...
            sprintf('Pico: día %.0f',dia_pico_act));
        hold(axTiempo,'off');
        legend(axTiempo,'Location','best');
        % ========================================================
        % PANEL DE RESULTADOS
        % ========================================================
         % ========================================================
        % MOSTRAR RESULTADOS
        % ========================================================
        textoResultados = sprintf( [ ...
            'ESCENARIO ACTUAL\n', ...
            '-----------------------------------------------\n', ...
            'R_0 = %.2f\n', ...
            'Personas infectadas alguna vez = %.0f (%.2f%%)\n', ...
            'Pico de infectados simultáneos = %.0f personas\n', ...
            'Día del pico = %.0f días\n', ...
            'AUC de I(t) = %.0f personas-día\n\n', ...
            'ESCENARIO DE REFERENCIA\n', ...
            '-----------------------------------------------\n', ...
            'R_0 = %.2f\n', ...
            'Personas infectadas alguna vez = %.0f (%.2f%%)\n', ...
            'Pico de infectados simultáneos = %.0f personas\n', ...
            'Día del pico = %.0f días\n', ...
            'AUC de I(t) = %.0f personas-día' ], ...
            R0_act, ...
            total_infectados_act, ...
            porcentaje_act, ...
            I_max_act, ...
            dia_pico_act, ...
            auc_act, ...
            R0_opt, ...
            total_infectados_opt, ...
            porcentaje_opt, ...
            I_max_opt, ...
            dia_pico_opt, ...
            auc_opt);
        lblResultados.Text = textoResultados;
    end
    % ============================================================
    % EXPORTAR AL WORKSPACE
    % ============================================================
    function exportarValores()
        beta_export = sldBeta.Value;
        gamma_export = sldGamma.Value;
        assignin('base','beta_seleccionado',beta_export);
        assignin('base','gamma_seleccionado',gamma_export);
        mensaje = sprintf( ...
            'Valores guardados:\nBeta = %.4f\nGamma = %.4f', ...
            beta_export,gamma_export);
        uialert( ...
            fig, ...
            mensaje, ...
            'Exportación exitosa', ...
            'Icon','success');
        fprintf( ...
            'Exportado al Workspace: beta = %.4f, gamma = %.4f\n', ...
            beta_export,gamma_export);
    end
end
% ================================================================
% MODELO SIR
% ================================================================
function dy = modeloSIR(~,y,beta,gamma,N)
    S = y(1);
    I = y(2);
    R = y(3);
    % Personas que pasan de susceptibles a infectadas
    nuevos_infectados = beta*S*I/N;
    % Personas que pasan de infectadas a recuperadas
    recuperaciones = gamma*I;
    % Ecuaciones SIR
    dS = -nuevos_infectados;
    dI = nuevos_infectados - recuperaciones;
    dR = recuperaciones;
    dy = [dS;dI;dR];
end